### ISSUE TITLE
CodeStar1403-FE-Phase04-Team07

### ISSUE THREAD

**Issue by asAlwaysZahra** [Star-Academy/codestar-intern-issues#803]
-   [ ] Introduction
-   [ ] Learning
    -   [ ] Box Model
        - [ ] Suppose we have a div with box-sizing set to border-box and a width of 100px. If we apply 20px of padding
          and 10px of margin, what is the actual width of this element? `120px`
        -   [ ] Units
            - [ ] Suppose we have a responsive page. Which unit do you prefer to use in this scenario? `relative units like em, rem, %, vw, vh. to ensure flexibility and adaptability across different screen sizes and resolutions. so we can create a responsive design that adapts gracefully to different devices and screen sizes.`
        -   [ ] Selectors
            - [ ] Suppose we have two nested divs: a parent div with className "a" and a child div with className "b". What is the difference between the ".a.b" and ".a .b" selectors? `.a.b: apply styles to element that has classes a and b combined. \
.a .b: style element with class b and parent with class a within the DOM.`
      -   [ ] Sass
            - [ ] Create a mixin that centers an element when it has the "box" className?
```css
@mixin center-element {
    display: flex;
    align-items: center;
    justify-content: center;
}

*:has(> .box) {
    @include center-element;
}
```
-   [ ] Project
    -  [ ] Read the project instruction from documents and write your answers.
        1. `your answer`
        2. `your answer`
        3. `your answer`
        4. `your answer`

**Comment by SaveAsArTaZ** [comment]
جواب Box Model اتون اشتباهه لطفا بیشتر دقت کنید

**Comment by SaveAsArTaZ** [comment]
Sass
ما داخل این سوال میخوایم میکسین بصورت جنرال اعمال بشه ولی فقط کلاس box تاثیر بپذیره

**Comment by asAlwaysZahra** [comment]
> جواب Box Model اتون اشتباهه لطفا بیشتر دقت کنید

100px

**Comment by SaveAsArTaZ** [comment]
> 100px

هنوز اشتباهه جواب ۱۴۰ میشه فردا توضیح میدم

**Comment by asAlwaysZahra** [comment]
> Sass ما داخل این سوال میخوایم میکسین بصورت جنرال اعمال بشه ولی فقط کلاس box تاثیر بپذیره

```scss
@mixin center-element($n) {
  #{$n} {
    display: flex;
    align-items: center;
    justify-content: center;
  }
}

* {
  @include center-element('*:has(> .box)');
}
```
